def line():
    Pen = input("Ingrese el coeficiente A: ")
    Pen = float(Pen)
    Od = input("Ingrese el coeficiente B: ")
    Od = float(Od) 
    X1 = input("Ingrese el coeficiente X1: ")
    X1 = float(X1)
    X2 = input("Ingrese el coeficiente X2: ")
    X2 = float(X2)
    Y1 = X1*Pen + Od
    Y2 = X2*Pen + Od
    DX12 = ((X2 - X1)**2 + (Y2 - Y1)**2)**(1/2)
    print(f"El coeficiente A de su ecuación de la recta es: {Pen}")
    print(f"El coeficiente B de su ecuación de la recta es: {Od}")
    print(f"El coeficiente X1 de su ecuación de la recta es: {X1}")
    print(f"El coeficiente X2 de su ecuación de la recta es: {X2}")
    print("")
    print("Para la siguiente ecuación:")
    print(f"\tY = {Pen}X + {Od}")
    print("")
    print("Dados los siguientes puntos:")
    print(f"\tP1 ({X1}, {Y1})")
    print(f"\tP2 ({X2}, {Y2})")
    print("")
    print(f"La distancia entre ellos es: {DX12}")
line()
